services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: volunteersDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment: 
     - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
     - 9000:9000
     - 9001:9001 
    volumes:
    - minio-data:/data
    command: server --console-address ":9001" /data

volumes:
  postgres-data:
  minio-data: