services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: volunteersDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
